### ISSUE TITLE
Files changed as a result of highstate are triggering the beacon

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble-salt#27]
_From @corleyma on October 13, 2016 21:28_

In my pillar, I have the following: 

```
beacons:
  pulsar:
    paths:
      - /var/cache/salt/minion/files/base/file-integrity-mon/conf/default.yaml
    disable_during_state_run: True
```

Despite that, I'm still seeing file changes that arise as a result of a highstate triggering the beacon/resulting in alerts sent to Slack.  In this case, the state results in the modification of a file that already existed on every host, not sure if that has anything to do with it.  

Still need to do more testing, but this beacon is going to be way too noisy if it triggers every time a state changes the filesystem.

_Copied from original issue: hubblestack/pulsar#47_
